registryItems:
  applications:
  - {xxl-job-scenario: nq 0}
  instances:
  - {xxl-job-scenario: 1}
  operationNames:
  - xxl-job-scenario: [
    "/requestmethod/xxljob",
  ]
segmentItems:
- applicationCode: spring-with-request-method-op-name-scenario
  segmentSize: nq 0
  segments:
  - segmentId: nq 0
    spans:
    - operationName: "/xxl-job-scenario/requestmethod/xxljob"
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: Http
      tags:
      - {key: "url", value: "http://localhost:8080/xxl-job-scenario/requestmethod/xxljob"}
      - {key: "http.method", value: "GET"}
      startTime: nq 0
      endTime: nq 0
      componentId: 13
      componentName: ""
      isError: false
      spanType: Exit
      peer: "localhost:8080"
      peerId: 0
    - operationName: "test.apache.skywalking.testcase.xxljob.handler.DemoJobHandler"
      operationId: 0
      parentSpanId: 0
      spanId: 2
      spanLayer: Http
      tags:
      - {key: "triggerParam", value: "xxljob"}
      startTime: nq 0
      endTime: nq 0
      componentId: 61
      componentName: "XXL_JOB"
      isError: false
      spanType: Exit
      peer: not null
      peerId: 0
