registryItems:
  applications:
  - {xxl-job-scenario: nq 0}
  instances:
  - {xxl-job-scenario: 1}
  operationNames:
  - xxl-job-scenario: [
    "test.apache.skywalking.testcase.xxljob.handler.DemoJobHandler"
  ]
segmentItems:
- applicationCode: xxl-job-scenario
  segmentSize: nq 0
  segments:
  - segmentId: nq 0
    spans:
    - operationName: "test.apache.skywalking.testcase.xxljob.handler.DemoJobHandler"
      operationId: 0
      parentSpanId: 0
      spanId: 2
      spanLayer: null
      tags:
      - {key: "triggerParam", value: "xxljob"}
      startTime: nq 0
      endTime: nq 0
      componentId: 61
      componentName: "XXL_JOB"
      isError: false
      spanType: Entry
      peer: not null
      peerId: 0
